### ISSUE TITLE
Can you add usage instructions? 

### ISSUE THREAD

**Issue by ghimiredhikura** [sarvanichinthapalli/HRel#1]
Hi, 

I read your paper. Congratulations. 
Can you add instructions regarding reproducing results in the paper? 

Kind Regards, 
Deepak

**Comment by sarvanichinthapalli** [comment]
Thanks for your interest.
Please run the file with the suffix 'ex.py' in the respective architectures.
At the end '.npz ' file is created with the Mutual information and sigma values for plotting.

**Comment by ghimiredhikura** [comment]
Thanks, @sarvanichinthapalli.
